import { StyleSheet } from 'react-native';
import colors from '../../../themes/colors';
import { font, fontSize } from '../../../themes';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: colors.white,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.textPrimary,
    fontFamily: font.nunitoBold,
  },
  searchContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 16,
    gap: 12,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 48,
    elevation: 2,
  },
  searchIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: colors.textPrimary,
    fontFamily: font.nunitoRegular,
  },
  filterButton: {
    width: 48,
    height: 48,
    backgroundColor: colors.white,
    elevation: 2,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterIcon: {
    fontSize: 20,
  },
  listContent: {
    padding: 20,

    backgroundColor: colors.cardBackground,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.textPrimary,
    fontFamily: font.nunitoBold,
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    color: colors.textSecondary,
    fontFamily: font.nunitoRegular,
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.primaryPink,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  fabIcon: {
    fontSize: 32,
    color: colors.white,
    fontWeight: '300',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuContainer: {
    backgroundColor: colors.white,
    borderRadius: 16,
    minWidth: 200,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },

  card: {
    backgroundColor: colors.white,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 16,
    marginBottom: 12,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    //alignItems: 'center',
    marginBottom: 12,
    //height: 24,
  },
  dropdown: {
    position: 'absolute',
    right: 28,
    top: 44,
    width: 106,
    backgroundColor: colors.white,
    paddingTop: 12,
    paddingRight: 10,
    paddingLeft: 8,
    borderRadius: 5,
    elevation: 2,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    zIndex: 3,
    paddingBottom: 2,
  },
  dropdownText: {
    fontSize: fontSize.average,
    lineHeight: 19,
    color: colors.black,
    marginLeft: 10,
    fontFamily: font.nunitoRegular,
  },
  dropdownButton: { flexDirection: 'row', height: 20, marginBottom: 10 },

  optionsButton: {
    paddingLeft: 10,
    paddingRight: 5,
    alignSelf: 'center',
  },
  optionsText: {
    fontSize: fontSize.large,
    color: colors.gray,
  },
  cardBody: {
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textPrimary,
    fontFamily: font.nunitoBold,
    marginBottom: 4,
  },
  previewText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontFamily: font.nunitoRegular,
    lineHeight: 20,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    paddingTop: 12,
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dateText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontFamily: font.nunitoMedium,
  },
  moodText: {
    fontSize: 18,
  },
  editedTimeText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontFamily: font.nunitoRegular,
    fontStyle: 'italic',
  },

  cardTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
});
